from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EmployeeViewSet, DepartmentViewSet, RoleViewSet

# The app_name helps with 'namespacing' (e.g., users:employee-list)
app_name = 'users'

# Create a router and register our viewsets
router = DefaultRouter()
router.register(r'employees', EmployeeViewSet, basename='employee')
router.register(r'departments', DepartmentViewSet, basename='department')
router.register(r'roles', RoleViewSet, basename='role')

urlpatterns = [
    # ==========================================================
    # USER MANAGEMENT ENDPOINTS
    # ==========================================================
    
    # This includes all the routes generated by the router
    # Paths will be: /api/v1/users/employees/, /api/v1/users/departments/, etc.
    path('', include(router.urls)),
]