# Generated by Django 5.1.3 on 2026-01-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_employee_pay_rate_alter_employee_pay_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('threshold_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_rules', to='users.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_rules', to='users.role')),
            ],
            options={
                'verbose_name': 'Overtime rule',
                'verbose_name_plural': 'Overtime rules',
            },
        ),
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hours_regular', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hours_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('overtime_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_entries', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='overtime.overtimerule')),
            ],
            options={
                'verbose_name': 'Overtime entry',
                'verbose_name_plural': 'Overtime entries',
                'unique_together': {('employee', 'rule', 'period_start', 'period_end')},
            },
        ),
    ]
