# Generated by Django 5.1.3 on 2025-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_department_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The monetary value based on the Pay Type.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_type',
            field=models.CharField(choices=[('HOURLY', 'Pay per Hour'), ('DAILY', 'Pay per Day'), ('MONTHLY', 'Monthly Salary')], default='Monthly', max_length=10),
        ),
    ]
