# Generated by Django 5.1.3 on 2026-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_pay_rate_employee_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base rate used for pay estimates (not full payroll).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_type',
            field=models.CharField(choices=[('HOURLY', 'Pay per Hour'), ('DAILY', 'Pay per Day'), ('MONTHLY', 'Monthly Salary')], default='MONTHLY', max_length=10),
        ),
    ]
