# Generated by Django 5.1.3 on 2025-12-30 12:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('total_work_duration', models.DurationField(default=datetime.timedelta)),
                ('total_overtime_duration', models.DurationField(default=datetime.timedelta)),
                ('expected_work_duration', models.DurationField(default=datetime.timedelta)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('ON_LEAVE', 'On leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'work_date'], name='attendance__employe_43991e_idx')],
                'unique_together': {('employee', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('clock_in_source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('KIOSK', 'Kiosk'), ('API', 'API')], default='WEB', max_length=20)),
                ('clock_out_source', models.CharField(blank=True, choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('AUTO_TIMEOUT', 'Auto timeout'), ('MANUAL_ADJUST', 'Manual adjust')], max_length=20, null=True)),
                ('is_manual_edit', models.BooleanField(default=False)),
                ('manual_edit_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_work_duration', models.DurationField(default=datetime.timedelta)),
                ('is_overtime', models.BooleanField(default=False)),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'work_date'], name='attendance__employe_c69d55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clock_out_at__isnull', True)), fields=('employee',), name='uniq_open_session_per_employee')],
            },
        ),
    ]
