# Generated by Django 5.1.3 on 2026-01-04 12:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancedaysummary_total_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedaysummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancedaysummary',
            name='expected_work_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AlterField(
            model_name='attendancedaysummary',
            name='total_overtime_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendancedaysummary',
            name='total_work_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='total_work_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
